import { defineField, defineType } from "sanity";

export const serviceType = defineType({
	name: "service",
	title: "Услуга",
	type: "document",
	groups: [
		{ name: "card", title: "Карточка" },
		{ name: "page", title: "Страница услуги" },
		{ name: "prices", title: "Цены" },
		{ name: "comparison", title: "До / после" },
		{ name: "seo", title: "SEO" },
	],
	fields: [
		defineField({ name: "active", title: "Показывать на сайте", type: "boolean", initialValue: true, group: "card" }),
		defineField({ name: "order", title: "Порядок", type: "number", initialValue: 10, group: "card", validation: (rule) => rule.required().integer().min(0) }),
		defineField({ name: "index", title: "Номер", type: "string", group: "card", validation: (rule) => rule.required() }),
		defineField({ name: "title", title: "Название", type: "string", group: "card", validation: (rule) => rule.required() }),
		defineField({ name: "slug", title: "Адрес страницы", type: "slug", group: "card", options: { source: "title" }, validation: (rule) => rule.required() }),
		defineField({ name: "lead", title: "Короткий акцент", type: "string", group: "card", validation: (rule) => rule.required() }),
		defineField({ name: "description", title: "Описание", type: "text", rows: 3, group: "card", validation: (rule) => rule.required() }),
		defineField({ name: "image", title: "Главная фотография", type: "image", group: "card", options: { hotspot: true } }),
		defineField({ name: "imagePath", title: "Резервное изображение", type: "string", readOnly: true, hidden: true }),
		defineField({ name: "duration", title: "Срок выполнения", type: "string", group: "page", description: "Например: 1–2 дня" }),
		defineField({ name: "outcomes", title: "Что получит клиент", type: "array", group: "page", of: [{ type: "string" }], validation: (rule) => rule.max(6) }),
		defineField({ name: "included", title: "Что входит в услугу", type: "array", group: "page", of: [{ type: "string" }] }),
		defineField({
			name: "process",
			title: "Этапы работы",
			type: "array",
			group: "page",
			of: [{
				type: "object",
				fields: [
					defineField({ name: "number", title: "Номер", type: "string" }),
					defineField({ name: "title", title: "Название", type: "string", validation: (rule) => rule.required() }),
					defineField({ name: "text", title: "Описание", type: "text", rows: 3, validation: (rule) => rule.required() }),
				],
				preview: { select: { title: "title", subtitle: "text" } },
			}],
		}),
		defineField({
			name: "faqs",
			title: "Вопросы по услуге",
			type: "array",
			group: "page",
			of: [{
				type: "object",
				fields: [
					defineField({ name: "question", title: "Вопрос", type: "string", validation: (rule) => rule.required() }),
					defineField({ name: "answer", title: "Ответ", type: "text", rows: 4, validation: (rule) => rule.required() }),
				],
				preview: { select: { title: "question", subtitle: "answer" } },
			}],
		}),
		defineField({ name: "priceFrom", title: "Цена от", type: "string", group: "prices", description: "Например: от 12 000 ₽" }),
		defineField({ name: "priceLead", title: "Пояснение к цене", type: "text", rows: 3, group: "prices" }),
		defineField({
			name: "priceOptions",
			title: "Варианты и комплексы",
			type: "array",
			group: "prices",
			of: [{
				type: "object",
				fields: [
					defineField({ name: "title", title: "Название", type: "string", validation: (rule) => rule.required() }),
					defineField({ name: "price", title: "Цена", type: "string", validation: (rule) => rule.required() }),
					defineField({ name: "description", title: "Короткое описание", type: "text", rows: 2 }),
					defineField({ name: "items", title: "Что входит", type: "array", of: [{ type: "string" }] }),
					defineField({ name: "featured", title: "Выделить как популярный", type: "boolean", initialValue: false }),
				],
				preview: { select: { title: "title", subtitle: "price" } },
			}],
		}),
		defineField({ name: "beforeImage", title: "Фотография ДО", type: "image", group: "comparison", options: { hotspot: true } }),
		defineField({ name: "afterImage", title: "Фотография ПОСЛЕ", type: "image", group: "comparison", options: { hotspot: true } }),
		defineField({ name: "comparisonCaption", title: "Подпись к сравнению", type: "text", rows: 3, group: "comparison" }),
		defineField({ name: "seoTitle", title: "SEO-заголовок", type: "string", group: "seo", validation: (rule) => rule.max(65).warning("Желательно до 65 символов") }),
		defineField({ name: "seoDescription", title: "SEO-описание", type: "text", rows: 3, group: "seo", validation: (rule) => rule.max(170).warning("Желательно до 170 символов") }),
	],
	preview: { select: { title: "title", subtitle: "lead", media: "image" } },
});
